### ISSUE TITLE
Windows test failure

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-gelf#5]
From https://github.com/elasticsearch/logstash/issues/2487

```
  49) inputs/gelf reads chunked gelf messages  inputs
     Failure/Error: block.call(pipeline, queue)
     SocketError:
       send: name or service not known
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'
```
